In [1]:
# https://pymongo.readthedocs.io/en/stable/

In [2]:
from pymongo import MongoClient

In [3]:
class Car:
    def __init__(self,marca):
        self.marca = marca
    def imprime(self):
        print("Coche",self.marca)
        
a = Car("VolksWagen")
b = Car("Volvo")

a.imprime()
b.imprime()

Coche VolksWagen
Coche Volvo

In [4]:
dbName = "companies"
client = MongoClient(f"mongodb://localhost/{dbName}")
db = client.get_database()
db

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'companies')

In [5]:
query = {"founded_month":10}
cursor = db.companies_new.find(query)
cursor

In [6]:
db.companies_new.find_one(query)

{'_id': ObjectId('52cdef7c4bab8bd675297d8a'),
 'name': 'Wetpaint',
 'permalink': 'abc2',
 'crunchbase_url': 'http://www.crunchbase.com/company/wetpaint',
 'homepage_url': 'http://wetpaint-inc.com',
 'blog_url': 'http://digitalquarters.net/',
 'blog_feed_url': 'http://digitalquarters.net/feed/',
 'twitter_username': 'BachelrWetpaint',
 'category_code': 'web',
 'number_of_employees': 47,
 'founded_year': 2005,
 'founded_month': 10,
 'founded_day': 17,
 'deadpooled_year': 1,
 'tag_list': 'wiki, seattle, elowitz, media-industry, media-platform, social-distribution-system',
 'alias_list': '',
 'email_address': 'info@wetpaint.com',
 'phone_number': '206.859.6300',
 'description': 'Technology Platform Company',
 'created_at': datetime.datetime(2007, 5, 25, 6, 51, 27),
 'updated_at': 'Sun Dec 08 07:15:44 UTC 2013',
 'overview': '<p>Wetpaint is a technology platform company that uses its proprietary state-of-the-art technology and expertise in social media to build and monetize audiences for digital publishers. Wetpaint’s own online property, Wetpaint Entertainment, an entertainment news site that attracts more than 12 million unique visitors monthly and has over 2 million Facebook fans, is a proof point to the company’s success in building and engaging audiences. Media companies can license Wetpaint’s platform which includes a dynamic playbook tailored to their individual needs and comprehensive training. Founded by Internet pioneer Ben Elowitz, and with offices in New York and Seattle, Wetpaint is backed by Accel Partners, the investors behind Facebook.</p>',
 'image': {'available_sizes': [[[150, 75],
    'assets/images/resized/0000/3604/3604v14-max-150x150.jpg'],
   [[250, 125], 'assets/images/resized/0000/3604/3604v14-max-250x250.jpg'],
   [[450, 225], 'assets/images/resized/0000/3604/3604v14-max-450x450.jpg']]},
 'products': [{'name': 'Wikison Wetpaint', 'permalink': 'wetpaint-wiki'},
  {'name': 'Wetpaint Social Distribution System',
   'permalink': 'wetpaint-social-distribution-system'}],
 'relationships': [{'is_past': False,
   'title': 'Co-Founder and VP, Social and Audience Development',
   'person': {'first_name': 'Michael',
    'last_name': 'Howell',
    'permalink': 'michael-howell'}},
  {'is_past': False,
   'title': 'Co-Founder/CEO/Board of Directors',
   'person': {'first_name': 'Ben',
    'last_name': 'Elowitz',
    'permalink': 'ben-elowitz'}},
  {'is_past': False,
   'title': 'COO/Board of Directors',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': False,
   'title': 'SVP, Strategy and Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Theresia',
    'last_name': 'Ranzetta',
    'permalink': 'theresia-ranzetta'}},
  {'is_past': False,
   'title': 'Board Member',
   'person': {'first_name': 'Gus',
    'last_name': 'Tai',
    'permalink': 'gus-tai'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Len',
    'last_name': 'Jordan',
    'permalink': 'len-jordan'}},
  {'is_past': False,
   'title': 'Head of Technology and Product',
   'person': {'first_name': 'Alex',
    'last_name': 'Weinstein',
    'permalink': 'alex-weinstein'}},
  {'is_past': True,
   'title': 'CFO',
   'person': {'first_name': 'Bert',
    'last_name': 'Hogue',
    'permalink': 'bert-hogue'}},
  {'is_past': True,
   'title': 'CFO/ CRO',
   'person': {'first_name': 'Brian',
    'last_name': 'Watkins',
    'permalink': 'brian-watkins'}},
  {'is_past': True,
   'title': 'Senior Vice President, Marketing',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': True,
   'title': 'VP, Technology and Product',
   'person': {'first_name': 'Werner',
    'last_name': 'Koepf',
    'permalink': 'werner-koepf'}},
  {'is_past': True,
   'title': 'VP Marketing',
   'person': {'first_name': 'Kevin',
    'last_name': 'Flaherty',
    'permalink': 'kevin-flaherty'}},
  {'is_past': True,
   'title': 'VP User Experience',
   'person': {'first_name': 'Alex',
    'last_name': 'Berg',
    'permalink': 'alex-berg'}},
  {'is_past': True,
   'title': 'VP Engineering',
   'person': {'first_name': 'Steve',
    'last_name': 'McQuade',
    'permalink': 'steve-mcquade'}},
  {'is_past': True,
   'title': 'Executive Editor',
   'person': {'first_name': 'Susan',
    'last_name': 'Mulcahy',
    'permalink': 'susan-mulcahy'}},
  {'is_past': True,
   'title': 'VP Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}}],
 'competitions': [{'competitor': {'name': 'Wikia', 'permalink': 'wikia'}},
  {'competitor': {'name': 'JotSpot', 'permalink': 'jotspot'}},
  {'competitor': {'name': 'Socialtext', 'permalink': 'socialtext'}},
  {'competitor': {'name': 'Ning by Glam Media', 'permalink': 'ning'}},
  {'competitor': {'name': 'Soceeo', 'permalink': 'soceeo'}},
  {'competitor': {'name': 'Yola', 'permalink': 'yola'}},
  {'competitor': {'name': 'SocialGO', 'permalink': 'socialgo'}},
  {'competitor': {'name': 'IslamNor', 'permalink': 'islamnor'}}],
 'providerships': [],
 'total_money_raised': '$39.8M',
 'funding_rounds': [{'id': 888,
   'round_code': 'a',
   'source_url': 'http://seattlepi.nwsource.com/business/246734_wiki02.html',
   'source_description': '',
   'raised_amount': 5250000,
   'raised_currency_code': 'USD',
   'funded_year': 2005,
   'funded_month': 10,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 889,
   'round_code': 'b',
   'source_url': 'http://pulse2.com/2007/01/09/wiki-builder-website-wetpaint-welcomes-95m-funding/',
   'source_description': '',
   'raised_amount': 9500000,
   'raised_currency_code': 'USD',
   'funded_year': 2007,
   'funded_month': 1,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 2312,
   'round_code': 'c',
   'source_url': 'http://www.accel.com/news/news_one_up.php?news_id=185',
   'source_description': 'Accel',
   'raised_amount': 25000000,
   'raised_currency_code': 'USD',
   'funded_year': 2008,
   'funded_month': 5,
   'funded_day': 19,
   'investments': [{'company': None,
     'financial_org': {'name': 'DAG Ventures', 'permalink': 'dag-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None}]}],
 'investments': [],
 'acquisition': {'price_amount': 30000000,
  'price_currency_code': 'USD',
  'term_code': 'cash_and_stock',
  'source_url': 'http://allthingsd.com/20131216/viggle-tries-to-bulk-up-its-social-tv-business-by-buying-wetpaint/?mod=atdtweet',
  'source_description': ' Viggle Tries to Bulk Up Its Social TV Business by Buying Wetpaint',
  'acquired_year': 2013,
  'acquired_month': 12,
  'acquired_day': 16,
  'acquiring_company': {'name': 'Viggle', 'permalink': 'viggle'}},
 'acquisitions': [],
 'offices': [{'description': '',
   'address1': '710 - 2nd Avenue',
   'address2': 'Suite 1100',
   'zip_code': '98104',
   'city': 'Seattle',
   'state_code': 'WA',
   'country_code': 'USA',
   'latitude': 47.603122,
   'longitude': -122.333253},
  {'description': '',
   'address1': '270 Lafayette Street',
   'address2': 'Suite 505',
   'zip_code': '10012',
   'city': 'New York',
   'state_code': 'NY',
   'country_code': 'USA',
   'latitude': 40.7237306,
   'longitude': -73.9964312}],
 'milestones': [{'id': 5869,
   'description': "Wetpaint named in Lead411's Hottest Seattle Companies list",
   'stoned_year': 2010,
   'stoned_month': 6,
   'stoned_day': 8,
   'source_url': 'http://www.lead411.com/seattle-companies.html',
   'source_text': None,
   'source_description': 'LEAD411 LAUNCHES "HOTTEST SEATTLE COMPANIES" AWARDS',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}},
  {'id': 8702,
   'description': 'Site-Builder Wetpaint Makes One For Itself, Using the Demand Media Playbook',
   'stoned_year': 2010,
   'stoned_month': 9,
   'stoned_day': 6,
   'source_url': 'http://mediamemo.allthingsd.com/20100906/site-builder-wetpaint-makes-one-for-itself-using-the-demand-media-playbook/',
   'source_text': None,
   'source_description': 'All Things D',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}}],
 'video_embeds': [],
 'screenshots': [{'available_sizes': [[[150, 86],
     'assets/images/resized/0016/0929/160929v2-max-150x150.png'],
    [[250, 143], 'assets/images/resized/0016/0929/160929v2-max-250x250.png'],
    [[450, 258], 'assets/images/resized/0016/0929/160929v2-max-450x450.png']],
   'attribution': None}],
 'external_links': [{'external_url': 'http://www.geekwire.com/2011/rewind-ben-elowitz-wetpaint-ceo-building-type-media-company',
   'title': 'GeekWire interview: Rewind - Ben Elowitz, Wetpaint CEO, on building a new type of media company'},
  {'external_url': 'http://techcrunch.com/2012/06/17/search-and-social-how-two-will-soon-become-one/',
   'title': 'Guest post by CEO Ben Elowitz in TechCrunch'},
  {'external_url': 'http://allthingsd.com/20120516/what-to-expect-when-facebook-is-expecting-five-predictions-for-facebooks-first-public-year/',
   'title': 'Guest post by CEO Ben Elowitz in AllThingsD'},
  {'external_url': 'http://adage.com/article/digitalnext/facebook-biggest-player-advertising-s-540-billion-world/235708/',
   'title': 'Guest post by CEO Ben Elowitz in AdAge'},
  {'external_url': 'http://www.businessinsider.com/facebook-captures-14-percent-of-our-online-attention-but-only-4-percent-of-ad-spending-online-2012-6',
   'title': 'Guest post by CEO Ben Elowitz in Business Insider'},
  {'external_url': 'http://allfacebook.com/wetpaint-media-data_b75963',
   'title': 'AllFacebook coverage of Wetpaint'},
  {'external_url': 'http://adage.com/article/digital/celeb-site-wetpaint-shows-media-profit-facebook/237828/',
   'title': 'Profile of Wetpaint in Ad Age'},
  {'external_url': 'http://allthingsd.com/20121018/how-to-boost-your-facebook-traffic-tips-and-tricks-from-wetpaint/',
   'title': 'Interview with Wetpaint CEO Ben Elowitz in All Things D'},
  {'external_url': 'http://www.xconomy.com/seattle/2012/10/19/wetpaint-starts-licensing-its-facebook-based-media-distribution-tech/',
   'title': 'Profile of Wetpaint in Xconomy'}],
 'partners': []}

In [7]:
data = list(cursor)

In [8]:
len(data)

605

In [9]:
data[0]

{'_id': ObjectId('52cdef7c4bab8bd675297d8a'),
 'name': 'Wetpaint',
 'permalink': 'abc2',
 'crunchbase_url': 'http://www.crunchbase.com/company/wetpaint',
 'homepage_url': 'http://wetpaint-inc.com',
 'blog_url': 'http://digitalquarters.net/',
 'blog_feed_url': 'http://digitalquarters.net/feed/',
 'twitter_username': 'BachelrWetpaint',
 'category_code': 'web',
 'number_of_employees': 47,
 'founded_year': 2005,
 'founded_month': 10,
 'founded_day': 17,
 'deadpooled_year': 1,
 'tag_list': 'wiki, seattle, elowitz, media-industry, media-platform, social-distribution-system',
 'alias_list': '',
 'email_address': 'info@wetpaint.com',
 'phone_number': '206.859.6300',
 'description': 'Technology Platform Company',
 'created_at': datetime.datetime(2007, 5, 25, 6, 51, 27),
 'updated_at': 'Sun Dec 08 07:15:44 UTC 2013',
 'overview': '<p>Wetpaint is a technology platform company that uses its proprietary state-of-the-art technology and expertise in social media to build and monetize audiences for digital publishers. Wetpaint’s own online property, Wetpaint Entertainment, an entertainment news site that attracts more than 12 million unique visitors monthly and has over 2 million Facebook fans, is a proof point to the company’s success in building and engaging audiences. Media companies can license Wetpaint’s platform which includes a dynamic playbook tailored to their individual needs and comprehensive training. Founded by Internet pioneer Ben Elowitz, and with offices in New York and Seattle, Wetpaint is backed by Accel Partners, the investors behind Facebook.</p>',
 'image': {'available_sizes': [[[150, 75],
    'assets/images/resized/0000/3604/3604v14-max-150x150.jpg'],
   [[250, 125], 'assets/images/resized/0000/3604/3604v14-max-250x250.jpg'],
   [[450, 225], 'assets/images/resized/0000/3604/3604v14-max-450x450.jpg']]},
 'products': [{'name': 'Wikison Wetpaint', 'permalink': 'wetpaint-wiki'},
  {'name': 'Wetpaint Social Distribution System',
   'permalink': 'wetpaint-social-distribution-system'}],
 'relationships': [{'is_past': False,
   'title': 'Co-Founder and VP, Social and Audience Development',
   'person': {'first_name': 'Michael',
    'last_name': 'Howell',
    'permalink': 'michael-howell'}},
  {'is_past': False,
   'title': 'Co-Founder/CEO/Board of Directors',
   'person': {'first_name': 'Ben',
    'last_name': 'Elowitz',
    'permalink': 'ben-elowitz'}},
  {'is_past': False,
   'title': 'COO/Board of Directors',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': False,
   'title': 'SVP, Strategy and Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Theresia',
    'last_name': 'Ranzetta',
    'permalink': 'theresia-ranzetta'}},
  {'is_past': False,
   'title': 'Board Member',
   'person': {'first_name': 'Gus',
    'last_name': 'Tai',
    'permalink': 'gus-tai'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Len',
    'last_name': 'Jordan',
    'permalink': 'len-jordan'}},
  {'is_past': False,
   'title': 'Head of Technology and Product',
   'person': {'first_name': 'Alex',
    'last_name': 'Weinstein',
    'permalink': 'alex-weinstein'}},
  {'is_past': True,
   'title': 'CFO',
   'person': {'first_name': 'Bert',
    'last_name': 'Hogue',
    'permalink': 'bert-hogue'}},
  {'is_past': True,
   'title': 'CFO/ CRO',
   'person': {'first_name': 'Brian',
    'last_name': 'Watkins',
    'permalink': 'brian-watkins'}},
  {'is_past': True,
   'title': 'Senior Vice President, Marketing',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': True,
   'title': 'VP, Technology and Product',
   'person': {'first_name': 'Werner',
    'last_name': 'Koepf',
    'permalink': 'werner-koepf'}},
  {'is_past': True,
   'title': 'VP Marketing',
   'person': {'first_name': 'Kevin',
    'last_name': 'Flaherty',
    'permalink': 'kevin-flaherty'}},
  {'is_past': True,
   'title': 'VP User Experience',
   'person': {'first_name': 'Alex',
    'last_name': 'Berg',
    'permalink': 'alex-berg'}},
  {'is_past': True,
   'title': 'VP Engineering',
   'person': {'first_name': 'Steve',
    'last_name': 'McQuade',
    'permalink': 'steve-mcquade'}},
  {'is_past': True,
   'title': 'Executive Editor',
   'person': {'first_name': 'Susan',
    'last_name': 'Mulcahy',
    'permalink': 'susan-mulcahy'}},
  {'is_past': True,
   'title': 'VP Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}}],
 'competitions': [{'competitor': {'name': 'Wikia', 'permalink': 'wikia'}},
  {'competitor': {'name': 'JotSpot', 'permalink': 'jotspot'}},
  {'competitor': {'name': 'Socialtext', 'permalink': 'socialtext'}},
  {'competitor': {'name': 'Ning by Glam Media', 'permalink': 'ning'}},
  {'competitor': {'name': 'Soceeo', 'permalink': 'soceeo'}},
  {'competitor': {'name': 'Yola', 'permalink': 'yola'}},
  {'competitor': {'name': 'SocialGO', 'permalink': 'socialgo'}},
  {'competitor': {'name': 'IslamNor', 'permalink': 'islamnor'}}],
 'providerships': [],
 'total_money_raised': '$39.8M',
 'funding_rounds': [{'id': 888,
   'round_code': 'a',
   'source_url': 'http://seattlepi.nwsource.com/business/246734_wiki02.html',
   'source_description': '',
   'raised_amount': 5250000,
   'raised_currency_code': 'USD',
   'funded_year': 2005,
   'funded_month': 10,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 889,
   'round_code': 'b',
   'source_url': 'http://pulse2.com/2007/01/09/wiki-builder-website-wetpaint-welcomes-95m-funding/',
   'source_description': '',
   'raised_amount': 9500000,
   'raised_currency_code': 'USD',
   'funded_year': 2007,
   'funded_month': 1,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 2312,
   'round_code': 'c',
   'source_url': 'http://www.accel.com/news/news_one_up.php?news_id=185',
   'source_description': 'Accel',
   'raised_amount': 25000000,
   'raised_currency_code': 'USD',
   'funded_year': 2008,
   'funded_month': 5,
   'funded_day': 19,
   'investments': [{'company': None,
     'financial_org': {'name': 'DAG Ventures', 'permalink': 'dag-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None}]}],
 'investments': [],
 'acquisition': {'price_amount': 30000000,
  'price_currency_code': 'USD',
  'term_code': 'cash_and_stock',
  'source_url': 'http://allthingsd.com/20131216/viggle-tries-to-bulk-up-its-social-tv-business-by-buying-wetpaint/?mod=atdtweet',
  'source_description': ' Viggle Tries to Bulk Up Its Social TV Business by Buying Wetpaint',
  'acquired_year': 2013,
  'acquired_month': 12,
  'acquired_day': 16,
  'acquiring_company': {'name': 'Viggle', 'permalink': 'viggle'}},
 'acquisitions': [],
 'offices': [{'description': '',
   'address1': '710 - 2nd Avenue',
   'address2': 'Suite 1100',
   'zip_code': '98104',
   'city': 'Seattle',
   'state_code': 'WA',
   'country_code': 'USA',
   'latitude': 47.603122,
   'longitude': -122.333253},
  {'description': '',
   'address1': '270 Lafayette Street',
   'address2': 'Suite 505',
   'zip_code': '10012',
   'city': 'New York',
   'state_code': 'NY',
   'country_code': 'USA',
   'latitude': 40.7237306,
   'longitude': -73.9964312}],
 'milestones': [{'id': 5869,
   'description': "Wetpaint named in Lead411's Hottest Seattle Companies list",
   'stoned_year': 2010,
   'stoned_month': 6,
   'stoned_day': 8,
   'source_url': 'http://www.lead411.com/seattle-companies.html',
   'source_text': None,
   'source_description': 'LEAD411 LAUNCHES "HOTTEST SEATTLE COMPANIES" AWARDS',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}},
  {'id': 8702,
   'description': 'Site-Builder Wetpaint Makes One For Itself, Using the Demand Media Playbook',
   'stoned_year': 2010,
   'stoned_month': 9,
   'stoned_day': 6,
   'source_url': 'http://mediamemo.allthingsd.com/20100906/site-builder-wetpaint-makes-one-for-itself-using-the-demand-media-playbook/',
   'source_text': None,
   'source_description': 'All Things D',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}}],
 'video_embeds': [],
 'screenshots': [{'available_sizes': [[[150, 86],
     'assets/images/resized/0016/0929/160929v2-max-150x150.png'],
    [[250, 143], 'assets/images/resized/0016/0929/160929v2-max-250x250.png'],
    [[450, 258], 'assets/images/resized/0016/0929/160929v2-max-450x450.png']],
   'attribution': None}],
 'external_links': [{'external_url': 'http://www.geekwire.com/2011/rewind-ben-elowitz-wetpaint-ceo-building-type-media-company',
   'title': 'GeekWire interview: Rewind - Ben Elowitz, Wetpaint CEO, on building a new type of media company'},
  {'external_url': 'http://techcrunch.com/2012/06/17/search-and-social-how-two-will-soon-become-one/',
   'title': 'Guest post by CEO Ben Elowitz in TechCrunch'},
  {'external_url': 'http://allthingsd.com/20120516/what-to-expect-when-facebook-is-expecting-five-predictions-for-facebooks-first-public-year/',
   'title': 'Guest post by CEO Ben Elowitz in AllThingsD'},
  {'external_url': 'http://adage.com/article/digitalnext/facebook-biggest-player-advertising-s-540-billion-world/235708/',
   'title': 'Guest post by CEO Ben Elowitz in AdAge'},
  {'external_url': 'http://www.businessinsider.com/facebook-captures-14-percent-of-our-online-attention-but-only-4-percent-of-ad-spending-online-2012-6',
   'title': 'Guest post by CEO Ben Elowitz in Business Insider'},
  {'external_url': 'http://allfacebook.com/wetpaint-media-data_b75963',
   'title': 'AllFacebook coverage of Wetpaint'},
  {'external_url': 'http://adage.com/article/digital/celeb-site-wetpaint-shows-media-profit-facebook/237828/',
   'title': 'Profile of Wetpaint in Ad Age'},
  {'external_url': 'http://allthingsd.com/20121018/how-to-boost-your-facebook-traffic-tips-and-tricks-from-wetpaint/',
   'title': 'Interview with Wetpaint CEO Ben Elowitz in All Things D'},
  {'external_url': 'http://www.xconomy.com/seattle/2012/10/19/wetpaint-starts-licensing-its-facebook-based-media-distribution-tech/',
   'title': 'Profile of Wetpaint in Xconomy'}],
 'partners': []}

In [10]:
print(type(data),type(data[0]))

<class 'list'> <class 'dict'>

In [11]:
list(cursor)

[]

In [12]:
# DO NOT DO THIS: You are geting 605 objects to use only the first ones
list(db.companies_new.find(query))[0]

{'_id': ObjectId('52cdef7c4bab8bd675297d8a'),
 'name': 'Wetpaint',
 'permalink': 'abc2',
 'crunchbase_url': 'http://www.crunchbase.com/company/wetpaint',
 'homepage_url': 'http://wetpaint-inc.com',
 'blog_url': 'http://digitalquarters.net/',
 'blog_feed_url': 'http://digitalquarters.net/feed/',
 'twitter_username': 'BachelrWetpaint',
 'category_code': 'web',
 'number_of_employees': 47,
 'founded_year': 2005,
 'founded_month': 10,
 'founded_day': 17,
 'deadpooled_year': 1,
 'tag_list': 'wiki, seattle, elowitz, media-industry, media-platform, social-distribution-system',
 'alias_list': '',
 'email_address': 'info@wetpaint.com',
 'phone_number': '206.859.6300',
 'description': 'Technology Platform Company',
 'created_at': datetime.datetime(2007, 5, 25, 6, 51, 27),
 'updated_at': 'Sun Dec 08 07:15:44 UTC 2013',
 'overview': '<p>Wetpaint is a technology platform company that uses its proprietary state-of-the-art technology and expertise in social media to build and monetize audiences for digital publishers. Wetpaint’s own online property, Wetpaint Entertainment, an entertainment news site that attracts more than 12 million unique visitors monthly and has over 2 million Facebook fans, is a proof point to the company’s success in building and engaging audiences. Media companies can license Wetpaint’s platform which includes a dynamic playbook tailored to their individual needs and comprehensive training. Founded by Internet pioneer Ben Elowitz, and with offices in New York and Seattle, Wetpaint is backed by Accel Partners, the investors behind Facebook.</p>',
 'image': {'available_sizes': [[[150, 75],
    'assets/images/resized/0000/3604/3604v14-max-150x150.jpg'],
   [[250, 125], 'assets/images/resized/0000/3604/3604v14-max-250x250.jpg'],
   [[450, 225], 'assets/images/resized/0000/3604/3604v14-max-450x450.jpg']]},
 'products': [{'name': 'Wikison Wetpaint', 'permalink': 'wetpaint-wiki'},
  {'name': 'Wetpaint Social Distribution System',
   'permalink': 'wetpaint-social-distribution-system'}],
 'relationships': [{'is_past': False,
   'title': 'Co-Founder and VP, Social and Audience Development',
   'person': {'first_name': 'Michael',
    'last_name': 'Howell',
    'permalink': 'michael-howell'}},
  {'is_past': False,
   'title': 'Co-Founder/CEO/Board of Directors',
   'person': {'first_name': 'Ben',
    'last_name': 'Elowitz',
    'permalink': 'ben-elowitz'}},
  {'is_past': False,
   'title': 'COO/Board of Directors',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': False,
   'title': 'SVP, Strategy and Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Theresia',
    'last_name': 'Ranzetta',
    'permalink': 'theresia-ranzetta'}},
  {'is_past': False,
   'title': 'Board Member',
   'person': {'first_name': 'Gus',
    'last_name': 'Tai',
    'permalink': 'gus-tai'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Len',
    'last_name': 'Jordan',
    'permalink': 'len-jordan'}},
  {'is_past': False,
   'title': 'Head of Technology and Product',
   'person': {'first_name': 'Alex',
    'last_name': 'Weinstein',
    'permalink': 'alex-weinstein'}},
  {'is_past': True,
   'title': 'CFO',
   'person': {'first_name': 'Bert',
    'last_name': 'Hogue',
    'permalink': 'bert-hogue'}},
  {'is_past': True,
   'title': 'CFO/ CRO',
   'person': {'first_name': 'Brian',
    'last_name': 'Watkins',
    'permalink': 'brian-watkins'}},
  {'is_past': True,
   'title': 'Senior Vice President, Marketing',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': True,
   'title': 'VP, Technology and Product',
   'person': {'first_name': 'Werner',
    'last_name': 'Koepf',
    'permalink': 'werner-koepf'}},
  {'is_past': True,
   'title': 'VP Marketing',
   'person': {'first_name': 'Kevin',
    'last_name': 'Flaherty',
    'permalink': 'kevin-flaherty'}},
  {'is_past': True,
   'title': 'VP User Experience',
   'person': {'first_name': 'Alex',
    'last_name': 'Berg',
    'permalink': 'alex-berg'}},
  {'is_past': True,
   'title': 'VP Engineering',
   'person': {'first_name': 'Steve',
    'last_name': 'McQuade',
    'permalink': 'steve-mcquade'}},
  {'is_past': True,
   'title': 'Executive Editor',
   'person': {'first_name': 'Susan',
    'last_name': 'Mulcahy',
    'permalink': 'susan-mulcahy'}},
  {'is_past': True,
   'title': 'VP Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}}],
 'competitions': [{'competitor': {'name': 'Wikia', 'permalink': 'wikia'}},
  {'competitor': {'name': 'JotSpot', 'permalink': 'jotspot'}},
  {'competitor': {'name': 'Socialtext', 'permalink': 'socialtext'}},
  {'competitor': {'name': 'Ning by Glam Media', 'permalink': 'ning'}},
  {'competitor': {'name': 'Soceeo', 'permalink': 'soceeo'}},
  {'competitor': {'name': 'Yola', 'permalink': 'yola'}},
  {'competitor': {'name': 'SocialGO', 'permalink': 'socialgo'}},
  {'competitor': {'name': 'IslamNor', 'permalink': 'islamnor'}}],
 'providerships': [],
 'total_money_raised': '$39.8M',
 'funding_rounds': [{'id': 888,
   'round_code': 'a',
   'source_url': 'http://seattlepi.nwsource.com/business/246734_wiki02.html',
   'source_description': '',
   'raised_amount': 5250000,
   'raised_currency_code': 'USD',
   'funded_year': 2005,
   'funded_month': 10,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 889,
   'round_code': 'b',
   'source_url': 'http://pulse2.com/2007/01/09/wiki-builder-website-wetpaint-welcomes-95m-funding/',
   'source_description': '',
   'raised_amount': 9500000,
   'raised_currency_code': 'USD',
   'funded_year': 2007,
   'funded_month': 1,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 2312,
   'round_code': 'c',
   'source_url': 'http://www.accel.com/news/news_one_up.php?news_id=185',
   'source_description': 'Accel',
   'raised_amount': 25000000,
   'raised_currency_code': 'USD',
   'funded_year': 2008,
   'funded_month': 5,
   'funded_day': 19,
   'investments': [{'company': None,
     'financial_org': {'name': 'DAG Ventures', 'permalink': 'dag-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None}]}],
 'investments': [],
 'acquisition': {'price_amount': 30000000,
  'price_currency_code': 'USD',
  'term_code': 'cash_and_stock',
  'source_url': 'http://allthingsd.com/20131216/viggle-tries-to-bulk-up-its-social-tv-business-by-buying-wetpaint/?mod=atdtweet',
  'source_description': ' Viggle Tries to Bulk Up Its Social TV Business by Buying Wetpaint',
  'acquired_year': 2013,
  'acquired_month': 12,
  'acquired_day': 16,
  'acquiring_company': {'name': 'Viggle', 'permalink': 'viggle'}},
 'acquisitions': [],
 'offices': [{'description': '',
   'address1': '710 - 2nd Avenue',
   'address2': 'Suite 1100',
   'zip_code': '98104',
   'city': 'Seattle',
   'state_code': 'WA',
   'country_code': 'USA',
   'latitude': 47.603122,
   'longitude': -122.333253},
  {'description': '',
   'address1': '270 Lafayette Street',
   'address2': 'Suite 505',
   'zip_code': '10012',
   'city': 'New York',
   'state_code': 'NY',
   'country_code': 'USA',
   'latitude': 40.7237306,
   'longitude': -73.9964312}],
 'milestones': [{'id': 5869,
   'description': "Wetpaint named in Lead411's Hottest Seattle Companies list",
   'stoned_year': 2010,
   'stoned_month': 6,
   'stoned_day': 8,
   'source_url': 'http://www.lead411.com/seattle-companies.html',
   'source_text': None,
   'source_description': 'LEAD411 LAUNCHES "HOTTEST SEATTLE COMPANIES" AWARDS',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}},
  {'id': 8702,
   'description': 'Site-Builder Wetpaint Makes One For Itself, Using the Demand Media Playbook',
   'stoned_year': 2010,
   'stoned_month': 9,
   'stoned_day': 6,
   'source_url': 'http://mediamemo.allthingsd.com/20100906/site-builder-wetpaint-makes-one-for-itself-using-the-demand-media-playbook/',
   'source_text': None,
   'source_description': 'All Things D',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}}],
 'video_embeds': [],
 'screenshots': [{'available_sizes': [[[150, 86],
     'assets/images/resized/0016/0929/160929v2-max-150x150.png'],
    [[250, 143], 'assets/images/resized/0016/0929/160929v2-max-250x250.png'],
    [[450, 258], 'assets/images/resized/0016/0929/160929v2-max-450x450.png']],
   'attribution': None}],
 'external_links': [{'external_url': 'http://www.geekwire.com/2011/rewind-ben-elowitz-wetpaint-ceo-building-type-media-company',
   'title': 'GeekWire interview: Rewind - Ben Elowitz, Wetpaint CEO, on building a new type of media company'},
  {'external_url': 'http://techcrunch.com/2012/06/17/search-and-social-how-two-will-soon-become-one/',
   'title': 'Guest post by CEO Ben Elowitz in TechCrunch'},
  {'external_url': 'http://allthingsd.com/20120516/what-to-expect-when-facebook-is-expecting-five-predictions-for-facebooks-first-public-year/',
   'title': 'Guest post by CEO Ben Elowitz in AllThingsD'},
  {'external_url': 'http://adage.com/article/digitalnext/facebook-biggest-player-advertising-s-540-billion-world/235708/',
   'title': 'Guest post by CEO Ben Elowitz in AdAge'},
  {'external_url': 'http://www.businessinsider.com/facebook-captures-14-percent-of-our-online-attention-but-only-4-percent-of-ad-spending-online-2012-6',
   'title': 'Guest post by CEO Ben Elowitz in Business Insider'},
  {'external_url': 'http://allfacebook.com/wetpaint-media-data_b75963',
   'title': 'AllFacebook coverage of Wetpaint'},
  {'external_url': 'http://adage.com/article/digital/celeb-site-wetpaint-shows-media-profit-facebook/237828/',
   'title': 'Profile of Wetpaint in Ad Age'},
  {'external_url': 'http://allthingsd.com/20121018/how-to-boost-your-facebook-traffic-tips-and-tricks-from-wetpaint/',
   'title': 'Interview with Wetpaint CEO Ben Elowitz in All Things D'},
  {'external_url': 'http://www.xconomy.com/seattle/2012/10/19/wetpaint-starts-licensing-its-facebook-based-media-distribution-tech/',
   'title': 'Profile of Wetpaint in Xconomy'}],
 'partners': []}

In [13]:
# Better approach: get only the first 5 documents
len(list(db.companies_new.find(query).limit(5)))

5

In [14]:
# Skip 5 items if you need it
list(db.companies_new.find(query).limit(2).skip(2))

[{'_id': ObjectId('52cdef7c4bab8bd675297d9d'),
  'name': 'Joost',
  'permalink': 'joost',
  'crunchbase_url': 'http://www.crunchbase.com/company/joost',
  'homepage_url': 'http://joost.com',
  'blog_url': 'http://blog.joost.com',
  'blog_feed_url': 'http://blog.joost.com/atom.xml',
  'twitter_username': None,
  'category_code': 'games_video',
  'number_of_employees': 0,
  'founded_year': 2006,
  'founded_month': 10,
  'founded_day': 1,
  'deadpooled_year': None,
  'deadpooled_month': None,
  'deadpooled_day': None,
  'deadpooled_url': None,
  'tag_list': 'iptv, babelgum, television, video, theveniceproject',
  'alias_list': None,
  'email_address': 'newyork@joost.com',
  'phone_number': '',
  'description': None,
  'created_at': 'Sat Jun 09 07:05:30 UTC 2007',
  'updated_at': 'Fri Mar 15 23:31:11 UTC 2013',
  'overview': '<p>As their third major undertaking, <a href="http://crunchbase.com/company/skype" title="Skype">Skype</a> and Kazaa founders Janus Friis and Niklas Zennstrom are attempting to perfect IPTV with Joost.  Joost is a p2p on demand video player that offers professional (legal) programming much like on your television, but whenever you want.  The service is free, however, there are video advertisements interspersed between and during programs as well as small type or image ads on the sides of your screen.</p>\n\n<p>With very heavy backing from media giants CBS and Viacom, Joost looks good to take on competitors <a href="http://crunchbase.com/company/bablegum" title="Bablegum">Bablegum</a> and <a href="http://www.techcrunch.com/2007/07/06/first-look-at-livestation-not-much-to-report/" title="Microsoft LiveStation">Microsoft LiveStation</a>.  Currently Joost has content deals with CNN, the NHL and Sony as well as their financiers CBS and Viacom (MTV, Comedy Central etc). They have also <a href="http://www.joost.com/forums/p/2007/08/widget-api/" title="recently" rel="nofollow">recently</a> developed a new Widget API open to third parties to make their own Joost widgets. </p>\n\n<p>Unlike many online video platforms, joost does require a download and cannot play video directly from users&#8217; browsers.  joost offers a desktop client that allows the user to watch on-demand TV over the internet. In addition, Joost enhances the TV experience by offering interactive tools. For example, users will be able to chat with friends while watching a show. The channels will also have interactive displays where users can discover behind-the-scene content.</p>\n\n<p>Joost&#8217;s peer-to-peer technology also lowers the cost of channel owners by reducing the amount of data the servers must stream out. joost only serves some selected users, while the rest of the data is distributed from user to user.  </p>\n\n<p>Rumor has it that Joost is in talks with hardware manufacturers to <a href="http://www.techcrunch.com/2007/06/15/embedded-joost-will-change-the-market/" title="embed">embed</a> its platform into TV set-top boxes. If the move were successful it could change the TV industry substantially.</p>\n\n<p>Joost is now fully public and open to all.</p>\n\n<p>UPDATE: Joost has recently deactivated it&#8217;s software client and now streams it&#8217;s entire catalog via Adobe&#8217;s Flash Player which is available for Windows, Mac OS X, and Linux.</p>',
  'image': {'available_sizes': [[[150, 64],
     'assets/images/resized/0000/3718/3718v1-max-150x150.png'],
    [[199, 85], 'assets/images/resized/0000/3718/3718v1-max-250x250.png'],
    [[199, 85], 'assets/images/resized/0000/3718/3718v1-max-450x450.png']],
   'attribution': None},
  'products': [{'name': 'Joost', 'permalink': 'joost'}],
  'relationships': [{'is_past': False,
    'title': 'CEO',
    'person': {'first_name': 'Matt',
     'last_name': 'Zelesko',
     'permalink': 'matt-zelesko'}},
   {'is_past': False,
    'title': 'Co-founder',
    'person': {'first_name': 'Janus',
     'last_name': 'Friis',
     'permalink': 'janus-friis'}},
   {'is_past': False,
    'title': 'Co-Founder',
    'person': {'first_name': 'Niklas',
     'last_name': 'Zennström',
     'permalink': 'niklas-zennstrom'}},
   {'is_past': True,
    'title': 'CEO',
    'person': {'first_name': 'Matthew',
     'last_name': 'Zelesko',
     'permalink': 'matthew-zelesko'}},
   {'is_past': True,
    'title': 'CEO',
    'person': {'first_name': 'Mike',
     'last_name': 'Volpi',
     'permalink': 'mike-volpi'}},
   {'is_past': True,
    'title': 'CTO',
    'person': {'first_name': 'Dirk-Willem',
     'last_name': 'van Gulik',
     'permalink': 'dirk-willem-van-gulik'}},
   {'is_past': True,
    'title': 'SVP of Sales',
    'person': {'first_name': 'Elizabeth',
     'last_name': 'Schiff',
     'permalink': 'elizabeth-schiff'}},
   {'is_past': True,
    'title': 'VP, Business Development',
    'person': {'first_name': 'Vipin',
     'last_name': 'Goyal',
     'permalink': 'vipin-goyal'}},
   {'is_past': True,
    'title': 'SVP Engineering',
    'person': {'first_name': 'Matt',
     'last_name': 'Zelesko',
     'permalink': 'matt-zelesko'}},
   {'is_past': True,
    'title': 'Backend systems architect',
    'person': {'first_name': 'Sylvain',
     'last_name': 'Wallez',
     'permalink': 'sylvain-wallez'}},
   {'is_past': True,
    'title': 'Director  of Operations',
    'person': {'first_name': 'Sander',
     'last_name': 'van Zoest',
     'permalink': 'sander-van-zoest'}},
   {'is_past': True,
    'title': 'Director of Business Development',
    'person': {'first_name': 'Aki',
     'last_name': 'Tsuchiya',
     'permalink': 'aki-tsuchiya'}},
   {'is_past': True,
    'title': 'Product Manager',
    'person': {'first_name': 'Esther',
     'last_name': 'Park',
     'permalink': 'esther-park'}},
   {'is_past': True,
    'title': 'Advisor',
    'person': {'first_name': 'Hiro',
     'last_name': 'Tamura',
     'permalink': 'hiro-tamura'}},
   {'is_past': True,
    'title': 'Board',
    'person': {'first_name': 'Mark',
     'last_name': 'Dyne',
     'permalink': 'mark-dyne'}},
   {'is_past': True,
    'title': 'Senior P2P Software Engineer',
    'person': {'first_name': 'Jens',
     'last_name': 'Finkhaeuser',
     'permalink': 'jens-finkhaeuser'}},
   {'is_past': True,
    'title': 'Creative Director',
    'person': {'first_name': 'Mark',
     'last_name': 'Webster',
     'permalink': 'mark-webster'}},
   {'is_past': True,
    'title': 'Senior Manager',
    'person': {'first_name': 'Allan',
     'last_name': 'Beaufour',
     'permalink': 'allan-beaufour'}},
   {'is_past': True,
    'title': 'Developer',
    'person': {'first_name': 'Kaare',
     'last_name': 'Larsen',
     'permalink': 'kaare-larsen'}}],
  'competitions': [{'competitor': {'name': 'Babelgum',
     'permalink': 'babelgum'}},
   {'competitor': {'name': 'Zattoo', 'permalink': 'zattoo'}},
   {'competitor': {'name': 'YouTube', 'permalink': 'youtube'}},
   {'competitor': {'name': 'Veoh', 'permalink': 'veoh'}},
   {'competitor': {'name': 'Vudu', 'permalink': 'vudu'}},
   {'competitor': {'name': 'Inuk Networks', 'permalink': 'inuk-networks'}},
   {'competitor': {'name': 'Participatory Culture Foundation',
     'permalink': 'participatory-culture-foundation'}},
   {'competitor': {'name': 'Next New Networks',
     'permalink': 'next-new-networks'}},
   {'competitor': {'name': 'hulu', 'permalink': 'hulu'}},
   {'competitor': {'name': 'hulu', 'permalink': 'hulu'}},
   {'competitor': {'name': 'MUBI', 'permalink': 'mubi'}}],
  'providerships': [],
  'total_money_raised': '$45M',
  'funding_rounds': [{'id': 19,
    'round_code': 'a',
    'source_url': 'http://www.lksf.org/eng/media/press/20070510.shtml',
    'source_description': 'Joost Announces $45 million Funding',
    'raised_amount': 45000000,
    'raised_currency_code': 'USD',
    'funded_year': 2007,
    'funded_month': 5,
    'funded_day': 9,
    'investments': [{'company': None,
      'financial_org': {'name': 'Sequoia Capital',
       'permalink': 'sequoia-capital'},
      'person': None},
     {'company': None,
      'financial_org': None,
      'person': {'first_name': 'Li',
       'last_name': 'Ka-shing',
       'permalink': 'li-ka-shing'}},
     {'company': None,
      'financial_org': {'name': 'Index Ventures',
       'permalink': 'index-ventures'},
      'person': None}]}],
  'investments': [],
  'acquisition': {'price_amount': None,
   'price_currency_code': 'USD',
   'term_code': None,
   'source_url': 'http://www.techcrunch.com/2009/11/24/joost-acquired-adconion/',
   'source_description': 'Joost Is Now Officially Dead â€“ Assets Acquired By Adconion Media Group',
   'acquired_year': 2009,
   'acquired_month': 11,
   'acquired_day': 24,
   'acquiring_company': {'name': 'Adconion Media Group',
    'permalink': 'adconion-media-group'}},
  'acquisitions': [],
  'offices': [{'description': '',
    'address1': '100 5th Ave Fl 6',
    'address2': '',
    'zip_code': '10011-6903',
    'city': 'New York',
    'state_code': 'NY',
    'country_code': 'USA',
    'latitude': 40.7464969,
    'longitude': -74.0094471}],
  'milestones': [{'id': 4860,
    'description': 'Joost Video Network Reaches 67 million Viewers/Month',
    'stoned_year': 2010,
    'stoned_month': 4,
    'stoned_day': 15,
    'source_url': 'http://techcrunch.com/2010/04/14/joost-video-network/',
    'source_text': '',
    'source_description': 'Joost Video Network Stuns With Big Reach: 67 Million Viewers Per Month ',
    'stoneable_type': 'Company',
    'stoned_value': None,
    'stoned_value_type': None,
    'stoned_acquirer': None,
    'stoneable': {'name': 'Joost', 'permalink': 'joost'}}],
  'ipo': None,
  'video_embeds': [{'embed_code': '<object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/2W2AZNo_cRI&hl=en&fs=&ap=%2526fmt%3D6"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/2W2AZNo_cRI&hl=en&fs=&ap=%2526fmt%3D6" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>\r\n<a href="SITELINK"> Joost iPhone App Review - AppVee.com</a>',
    'description': ''},
   {'embed_code': '<embed src="http://blip.tv/play/goRr3o02AA%2Em4v" type="application/x-shockwave-flash" width="370" height="308" allowscriptaccess="always" allowfullscreen="true"></embed>',
    'description': '<p>This video was originally published on <a href="http://www.beet.tv/2008/12/joost-launches.html" title="Beet.TV" rel="nofollow">Beet.TV</a></p>'}],
  'screenshots': [],
  'external_links': [],
  'partners': []},
 {'_id': ObjectId('52cdef7c4bab8bd675297da4'),
  'name': 'Powerset',
  'permalink': 'powerset',
  'crunchbase_url': 'http://www.crunchbase.com/company/powerset',
  'homepage_url': 'http://powerset.com',
  'blog_url': 'http://blog.powerset.com/',
  'blog_feed_url': 'http://blog.powerset.com/atom.xml',
  'twitter_username': 'Powerset',
  'category_code': 'search',
  'number_of_employees': 60,
  'founded_year': 2006,
  'founded_month': 10,
  'founded_day': None,
  'deadpooled_year': None,
  'deadpooled_month': None,
  'deadpooled_day': None,
  'deadpooled_url': None,
  'tag_list': 'searchengine, google, techcrunch40, natural-language',
  'alias_list': '',
  'email_address': 'info@powerset.com',
  'phone_number': '415-848-7000',
  'description': '',
  'created_at': 'Mon Jun 11 19:33:13 UTC 2007',
  'updated_at': 'Sat Mar 16 06:13:05 UTC 2013',
  'overview': '<p>Powerset is a search engine focused on natural language processing. In other words, Powerset will not search based simply on keywords alone, but will try to understand the semantic meaning behind the search phrase as a whole. The company <a href="http://www.techcrunch.com/2008/05/11/powerset-launches-showcase-for-user-search-experience/" title="launched">launched</a> in May 2008 with intentions of making search more easy and intuitive.</p>\n\n<p>Powerset was acquired by <a href="/company/microsoft" title="Microsoft" rel="nofollow">Microsoft</a> on 1st July 2008.</p>',
  'image': {'available_sizes': [[[150, 38],
     'assets/images/resized/0000/3934/3934v1-max-150x150.png'],
    [[231, 59], 'assets/images/resized/0000/3934/3934v1-max-250x250.png'],
    [[231, 59], 'assets/images/resized/0000/3934/3934v1-max-450x450.png']],
   'attribution': None},
  'products': [{'name': 'Powerset', 'permalink': 'powerset'}],
  'relationships': [{'is_past': False,
    'title': 'Founder / Product Architect',
    'person': {'first_name': 'Lorenzo',
     'last_name': 'Thione',
     'permalink': 'lorenzo-thione'}},
   {'is_past': False,
    'title': 'Chief Science Officer',
    'person': {'first_name': 'Ron',
     'last_name': 'Kaplan',
     'permalink': 'ron-kaplan'}},
   {'is_past': False,
    'title': 'Investor',
    'person': {'first_name': 'Eric',
     'last_name': 'Tilenius',
     'permalink': 'eric-tilenius'}},
   {'is_past': False,
    'title': 'Board of Directors',
    'person': {'first_name': 'Luke',
     'last_name': 'Nosek',
     'permalink': 'luke-nosek'}},
   {'is_past': False,
    'title': 'General Manager & Director of Product',
    'person': {'first_name': 'Scott',
     'last_name': 'Prevost',
     'permalink': 'scott-prevost'}},
   {'is_past': False,
    'title': 'Director of Finance',
    'person': {'first_name': 'Bennett',
     'last_name': 'Thuener',
     'permalink': 'bennett-thuener'}},
   {'is_past': True,
    'title': 'COO, Founder, Board',
    'person': {'first_name': 'Steve',
     'last_name': 'Newcomb',
     'permalink': 'steve-newcomb'}},
   {'is_past': True,
    'title': 'Board / Founder / CEO',
    'person': {'first_name': 'Barney',
     'last_name': 'Pell',
     'permalink': 'barney-pell'}},
   {'is_past': True,
    'title': 'Investor',
    'person': {'first_name': 'Pejman',
     'last_name': 'Nozad',
     'permalink': 'pejman-nozad'}},
   {'is_past': True,
    'title': 'Board of Directors',
    'person': {'first_name': 'Scott',
     'last_name': 'Banister',
     'permalink': 'scott-banister'}},
   {'is_past': True,
    'title': 'Scientist, Ranking & Search Relevance',
    'person': {'first_name': 'Jonathan',
     'last_name': 'Siddharth',
     'permalink': 'jonathan-siddharth'}},
   {'is_past': True,
    'title': 'Software Engineer',
    'person': {'first_name': 'Alex',
     'last_name': 'Le',
     'permalink': 'alex-le'}},
   {'is_past': True,
    'title': 'Manager of Knowledge Resources',
    'person': {'first_name': 'John',
     'last_name': 'Lowe',
     'permalink': 'john-lowe-2'}},
   {'is_past': True,
    'title': 'Product Manager',
    'person': {'first_name': 'Mark',
     'last_name': 'Johnson',
     'permalink': 'mark-johnson-4'}},
   {'is_past': True,
    'title': 'Board of Directors',
    'person': {'first_name': 'Peter',
     'last_name': 'Thiel',
     'permalink': 'peter-thiel'}},
   {'is_past': True,
    'title': 'General Manager and Director of Product',
    'person': {'first_name': 'Scott',
     'last_name': 'Prevost',
     'permalink': 'scott-prevost'}},
   {'is_past': True,
    'title': 'Investor',
    'person': {'first_name': 'Bill',
     'last_name': 'Trenchard',
     'permalink': 'bill-trenchard'}},
   {'is_past': True,
    'title': 'Director of Operations',
    'person': {'first_name': 'bill',
     'last_name': 'fumerola',
     'permalink': 'bill-fumerola'}},
   {'is_past': True,
    'title': 'Investor (acquired by Microsoft)',
    'person': {'first_name': 'Mohsen',
     'last_name': 'Moazami',
     'permalink': 'mohsen-moazami'}},
   {'is_past': True,
    'title': 'Software Developer',
    'person': {'first_name': 'Tom',
     'last_name': 'Preston-Werner',
     'permalink': 'tom-preston-werner'}}],
  'competitions': [{'competitor': {'name': 'Hakia', 'permalink': 'hakia'}},
   {'competitor': {'name': 'TextWise', 'permalink': 'textwise'}},
   {'competitor': {'name': 'ChaCha', 'permalink': 'chacha'}},
   {'competitor': {'name': 'Google', 'permalink': 'google'}},
   {'competitor': {'name': 'Yahoo!', 'permalink': 'yahoo'}},
   {'competitor': {'name': 'Microsoft', 'permalink': 'microsoft'}},
   {'competitor': {'name': 'Blekko', 'permalink': 'blekko'}},
   {'competitor': {'name': 'JIxperts', 'permalink': 'jixperts'}},
   {'competitor': {'name': 'Viewzi', 'permalink': 'viewzi'}},
   {'competitor': {'name': 'Gloofi', 'permalink': 'gloofi'}},
   {'competitor': {'name': 'Cognition Technologies',
     'permalink': 'cognition-technologies'}},
   {'competitor': {'name': 'Devtap', 'permalink': 'devtap'}},
   {'competitor': {'name': 'CDNPAL', 'permalink': 'cdnpal'}}],
  'providerships': [{'title': '',
    'is_past': False,
    'provider': {'name': 'SHIFT Communications',
     'permalink': 'shift-communications'}}],
  'total_money_raised': '$22.5M',
  'funding_rounds': [{'id': 22,
    'round_code': 'a',
    'source_url': 'http://www.powerset.com/press/seriesa, http://venturebeat.com/2007/11/02/powerset-the-hyped-search-engine-company-sees-shakeup/#more-52474',
    'source_description': '',
    'raised_amount': 12500000,
    'raised_currency_code': 'USD',
    'funded_year': 2007,
    'funded_month': 6,
    'funded_day': 1,
    'investments': [{'company': None,
      'financial_org': {'name': 'Foundation Capital',
       'permalink': 'foundation-capital'},
      'person': None},
     {'company': None,
      'financial_org': {'name': 'Founders Fund', 'permalink': 'founders-fund'},
      'person': None},
     {'company': None,
      'financial_org': None,
      'person': {'first_name': 'Scott',
       'last_name': 'Banister',
       'permalink': 'scott-banister'}},
     {'company': None,
      'financial_org': {'name': 'Bezos Expeditions',
       'permalink': 'bezos-expeditions'},
      'person': None},
     {'company': None,
      'financial_org': None,
      'person': {'first_name': 'Reid',
       'last_name': 'Hoffman',
       'permalink': 'reid-hoffman'}}]},
   {'id': 2827,
    'round_code': 'debt_round',
    'source_url': 'http://www.techcrunch.com/2008/07/01/ok-now-its-done-microsoft-to-acquire-powerset/',
    'source_description': 'Ok, Now Itâ€™s Done. Microsoft To Acquire Powerset',
    'raised_amount': 8000000,
    'raised_currency_code': 'USD',
    'funded_year': 2007,
    'funded_month': 1,
    'funded_day': 1,
    'investments': []},
   {'id': 13872,
    'round_code': 'unattributed',
    'source_url': '',
    'source_description': 'EDGAR',
    'raised_amount': 2000000,
    'raised_currency_code': 'USD',
    'funded_year': 2006,
    'funded_month': 5,
    'funded_day': 1,
    'investments': [{'company': None,
      'financial_org': {'name': 'Amidzad Partners',
       'permalink': 'amidzad-partners'},
      'person': None},
     {'company': None,
      'financial_org': {'name': 'CommerceNet', 'permalink': 'commercenet'},
      'person': None},
     {'company': {'name': 'ValleyVC', 'permalink': 'valleyvc'},
      'financial_org': None,
      'person': None}]}],
  'investments': [],
  'acquisition': {'price_amount': 100000000,
   'price_currency_code': 'USD',
   'term_code': 'cash',
   'source_url': 'http://www.powerset.com/blog/articles/2008/07/01/microsoft-to-acquire-powerset',
   'source_description': 'Microsoft to Acquire Powerset',
   'acquired_year': 2008,
   'acquired_month': 7,
   'acquired_day': 1,
   'acquiring_company': {'name': 'Microsoft', 'permalink': 'microsoft'}},
  'acquisitions': [],
  'offices': [{'description': None,
    'address1': '475 Brannan St',
    'address2': '',
    'zip_code': '94107',
    'city': 'San Francisco',
    'state_code': 'CA',
    'country_code': 'USA',
    'latitude': 37.778613,
    'longitude': -122.395289}],
  'milestones': [],
  'ipo': None,

In [16]:
cur = db.companies_new.find(query)

In [17]:
data = list(cur)

In [19]:
cur.explain()

{'queryPlanner': {'plannerVersion': 1,
  'namespace': 'companies.companies_new',
  'indexFilterSet': False,
  'parsedQuery': {'founded_month': {'$eq': 10}},
  'winningPlan': {'stage': 'COLLSCAN',
   'filter': {'founded_month': {'$eq': 10}},
   'direction': 'forward'},
  'rejectedPlans': []},
 'executionStats': {'executionSuccess': True,
  'nReturned': 605,
  'executionTimeMillis': 26,
  'totalKeysExamined': 0,
  'totalDocsExamined': 18801,
  'executionStages': {'stage': 'COLLSCAN',
   'filter': {'founded_month': {'$eq': 10}},
   'nReturned': 605,
   'executionTimeMillisEstimate': 0,
   'works': 18803,
   'advanced': 605,
   'needTime': 18197,
   'needYield': 0,
   'saveState': 146,
   'restoreState': 146,
   'isEOF': 1,
   'direction': 'forward',
   'docsExamined': 18801},
  'allPlansExecution': []},
 'serverInfo': {'host': 'mbpmarc.local',
  'port': 27017,
  'version': '4.2.1',
  'gitVersion': 'edf6d45851c0b9ee15548f0f847df141764a317e'},
 'ok': 1.0}

In [20]:
cur.alive

False

In [29]:
import pandas as pd
df = pd.DataFrame(db.companies_new.find(query))
display(df[["name","offices"]])

,name,offices
0,Wetpaint,"[{'description': '', 'address1': '710 - 2nd Av..."
1,Digg,"[{'description': None, 'address1': '135 Missis..."
2,Joost,"[{'description': '', 'address1': '100 5th Ave ..."
3,Powerset,"[{'description': None, 'address1': '475 Branna..."
4,TheFind,"[{'description': '', 'address1': '310 Villa St..."
...,...,...
600,Embarcadero Technologies,"[{'description': 'Corporate Headquarters', 'ad..."
601,Bump Technologies,"[{'description': 'HQ', 'address1': '', 'addres..."
602,Fotothing,"[{'description': 'ADVFN plc, Owners', 'address..."
603,CScout Japan,"[{'description': 'CScout Japan Co., Ltd.', 'ad..."
604,My TV Shows,"[{'description': 'Lisbon Office', 'address1': ..."

In [24]:
df[["name","offices"]].explode("offices")

,name,offices
0,Wetpaint,"{'description': '', 'address1': '710 - 2nd Ave..."
0,Wetpaint,"{'description': '', 'address1': '270 Lafayette..."
1,Digg,"{'description': None, 'address1': '135 Mississ..."
2,Joost,"{'description': '', 'address1': '100 5th Ave F..."
3,Powerset,"{'description': None, 'address1': '475 Brannan..."
...,...,...
600,Embarcadero Technologies,"{'description': 'Corporate Headquarters', 'add..."
601,Bump Technologies,"{'description': 'HQ', 'address1': '', 'address..."
602,Fotothing,"{'description': 'ADVFN plc, Owners', 'address1..."
603,CScout Japan,"{'description': 'CScout Japan Co., Ltd.', 'add..."
604,My TV Shows,"{'description': 'Lisbon Office', 'address1': '..."

In [28]:
q = df[["name","offices"]].explode("offices")
q.apply(lambda reg: reg["offices"], axis=1, result_type="expand")

,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253
0,,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431
1,None,135 Mississippi St,,94107,San Francisco,CA,USA,37.764726,-122.394523
2,,100 5th Ave Fl 6,,10011-6903,New York,NY,USA,40.746497,-74.009447
3,None,475 Brannan St,,94107,San Francisco,CA,USA,37.778613,-122.395289
...,...,...,...,...,...,...,...,...,...
600,Corporate Headquarters,100 California Street,12th Floor,94111,San Francisco,CA,USA,37.793949,-122.398062
601,HQ,,,94041,Mountain View,CA,USA,NaN,NaN
602,"ADVFN plc, Owners",26 Throgmorton Street,,EC2 2AN,London,None,GBR,NaN,NaN
603,"CScout Japan Co., Ltd.",Hanegi 2-17-8,Setagaya-ku,156-0042,Tokyo,None,JPN,NaN,NaN
604,Lisbon Office,Rua RosÃ¡lia de Castro,,1700,Lisbon,None,PRT,38.752367,-9.146221

In [31]:
m = pd.DataFrame([
    {"name":"Pepe", "colors":["Blue","Red","Green"]},
    {"name":"Luis", "colors":["Orange", "Yellow"]}
])
m

   name              colors
0  Pepe  [Blue, Red, Green]
1  Luis    [Orange, Yellow]

In [32]:
m.explode("colors")

   name  colors
0  Pepe    Blue
0  Pepe     Red
0  Pepe   Green
1  Luis  Orange
1  Luis  Yellow

In [33]:
m1 = pd.DataFrame([
    {"name":"Pepe", "colors":[{"colorName":"Blue","percent":30},{"colorName":"Red","percent":80},{"colorName":"Green","percent":10}]},
    {"name":"Luis", "colors":[{"colorName":"Orange","percent":95},{"colorName":"Yellow","percent":5}]}
])
m1

   name                                             colors
0  Pepe  [{'colorName': 'Blue', 'percent': 30}, {'color...
1  Luis  [{'colorName': 'Orange', 'percent': 95}, {'col...

In [39]:
exploded = m1.explode("colors")
display(exploded)
expanded = exploded.apply(lambda reg:reg.colors, axis=1, result_type="expand")
display(expanded)
pd.concat([exploded,expanded], axis=1)[["name","colorName","percent"]]

   name                                  colors
0  Pepe    {'colorName': 'Blue', 'percent': 30}
0  Pepe     {'colorName': 'Red', 'percent': 80}
0  Pepe   {'colorName': 'Green', 'percent': 10}
1  Luis  {'colorName': 'Orange', 'percent': 95}
1  Luis   {'colorName': 'Yellow', 'percent': 5}

  colorName  percent
0      Blue       30
0       Red       80
0     Green       10
1    Orange       95
1    Yellow        5

   name colorName  percent
0  Pepe      Blue       30
0  Pepe       Red       80
0  Pepe     Green       10
1  Luis    Orange       95
1  Luis    Yellow        5

In [47]:
m1 = pd.DataFrame([
    {"name":"Pepe", "colors":[{"colorName":"Blue","percent":30},{"colorName":"Red","percent":80},{"colorName":"Green","percent":10}]},
    {"name":"Luis", "colors":[{"colorName":"Orange","percent":95},{"colorName":"Yellow","percent":5}]}
])
exploded = m1.explode("colors")
display(exploded)

def transformer(registro):
    print(registro)
    return {
        "name":registro["name"],
        **registro.colors
    }

expanded = exploded.apply(transformer, axis=1, result_type="expand")
display(expanded)

   name                                  colors
0  Pepe    {'colorName': 'Blue', 'percent': 30}
0  Pepe     {'colorName': 'Red', 'percent': 80}
0  Pepe   {'colorName': 'Green', 'percent': 10}
1  Luis  {'colorName': 'Orange', 'percent': 95}
1  Luis   {'colorName': 'Yellow', 'percent': 5}

name                                      Pepe
colors    {'colorName': 'Blue', 'percent': 30}
Name: 0, dtype: object
name                                     Pepe
colors    {'colorName': 'Red', 'percent': 80}
Name: 0, dtype: object
name                                       Pepe
colors    {'colorName': 'Green', 'percent': 10}
Name: 0, dtype: object
name                                        Luis
colors    {'colorName': 'Orange', 'percent': 95}
Name: 1, dtype: object
name                                       Luis
colors    {'colorName': 'Yellow', 'percent': 5}
Name: 1, dtype: object

   name colorName  percent
0  Pepe      Blue       30
0  Pepe       Red       80
0  Pepe     Green       10
1  Luis    Orange       95
1  Luis    Yellow        5

In [52]:
m1 = pd.DataFrame([
    {"name":"Pepe", "colors":[{"colorName":"Blue","percent":30},{"colorName":"Red","percent":80},{"colorName":"Green","percent":10}]},
    {"name":"Luis", "colors":[{"colorName":"Orange","percent":95},{"colorName":"Yellow","percent":5}]}
])
exploded = m1.explode("colors")
display(exploded)

withFieldsExpand = lambda fields, toExpand: lambda reg: {**{ field:reg[field] for field in fields },**reg[toExpand]}

expanded = exploded.apply(withFieldsExpand(["name"],"colors"), axis=1, result_type="expand")
display(expanded)

   name                                  colors
0  Pepe    {'colorName': 'Blue', 'percent': 30}
0  Pepe     {'colorName': 'Red', 'percent': 80}
0  Pepe   {'colorName': 'Green', 'percent': 10}
1  Luis  {'colorName': 'Orange', 'percent': 95}
1  Luis   {'colorName': 'Yellow', 'percent': 5}

   name colorName  percent
0  Pepe      Blue       30
0  Pepe       Red       80
0  Pepe     Green       10
1  Luis    Orange       95
1  Luis    Yellow        5

In [53]:
df = pd.DataFrame(db.companies_new.find(query))

In [59]:
withFieldsExpand = lambda fields, toExpand: lambda reg: {**{ field:reg[field] for field in fields },**reg[toExpand]}
df[["name","offices"]].explode("offices").apply(withFieldsExpand(["name"],"offices"), axis=1,result_type="expand")

TypeError: 'float' object is not a mapping

# Get a dataframe where each row is a company office

In [99]:
# Get a dataframe where each row is a company office
print(query)
df = pd.DataFrame(db.companies_new.find(query))
q = df[["name","offices"]].explode("offices")
data = q.apply(lambda reg: reg["offices"], axis=1, result_type="expand")
df2 = pd.concat([df["name"],data],axis=1)
df2

{'founded_month': 10}

,name,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,Wetpaint,,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253
0,Wetpaint,,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431
1,Digg,None,135 Mississippi St,,94107,San Francisco,CA,USA,37.764726,-122.394523
2,Joost,,100 5th Ave Fl 6,,10011-6903,New York,NY,USA,40.746497,-74.009447
3,Powerset,None,475 Brannan St,,94107,San Francisco,CA,USA,37.778613,-122.395289
...,...,...,...,...,...,...,...,...,...,...
600,Embarcadero Technologies,Corporate Headquarters,100 California Street,12th Floor,94111,San Francisco,CA,USA,37.793949,-122.398062
601,Bump Technologies,HQ,,,94041,Mountain View,CA,USA,NaN,NaN
602,Fotothing,"ADVFN plc, Owners",26 Throgmorton Street,,EC2 2AN,London,None,GBR,NaN,NaN
603,CScout Japan,"CScout Japan Co., Ltd.",Hanegi 2-17-8,Setagaya-ku,156-0042,Tokyo,None,JPN,NaN,NaN
604,My TV Shows,Lisbon Office,Rua RosÃ¡lia de Castro,,1700,Lisbon,None,PRT,38.752367,-9.146221

# GOAL: convert 2 columns into a geoJSON object

```json
{
  "type": "Point",
  "coordinates": [
    47.603122,
    -122.333253
  ]
}
```

In [106]:
import math
def toGeoJson(longitude,latitude):
    try:
        latitude = float(latitude)
        longitude = float(longitude)
        if math.isnan(latitude) or math.isnan(longitude):
            return None
        return {
            "type":"Point",
            "coordinates":[
                longitude,
                latitude,
            ]
        }
    except Exception:
        return None

In [93]:
toGeoJson("33","44")

{'type': 'Point', 'coordinates': [44.0, 33.0]}

In [94]:
toGeoJson(33,"44")

{'type': 'Point', 'coordinates': [44.0, 33.0]}

In [95]:
toGeoJson(33,"44a")

In [108]:
df2["geopoint"] = df2.apply(lambda reg: toGeoJson(reg.longitude,reg.latitude) ,axis=1)

In [97]:
df2

,name,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude,geopoint
0,Wetpaint,,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253,"{'type': 'Point', 'coordinates': [-122.333253,..."
0,Wetpaint,,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431,"{'type': 'Point', 'coordinates': [-73.9964312,..."
1,Digg,None,135 Mississippi St,,94107,San Francisco,CA,USA,37.764726,-122.394523,"{'type': 'Point', 'coordinates': [-122.394523,..."
2,Joost,,100 5th Ave Fl 6,,10011-6903,New York,NY,USA,40.746497,-74.009447,"{'type': 'Point', 'coordinates': [-74.0094471,..."
3,Powerset,None,475 Brannan St,,94107,San Francisco,CA,USA,37.778613,-122.395289,"{'type': 'Point', 'coordinates': [-122.395289,..."
...,...,...,...,...,...,...,...,...,...,...,...
600,Embarcadero Technologies,Corporate Headquarters,100 California Street,12th Floor,94111,San Francisco,CA,USA,37.793949,-122.398062,"{'type': 'Point', 'coordinates': [-122.398062,..."
601,Bump Technologies,HQ,,,94041,Mountain View,CA,USA,NaN,NaN,None
602,Fotothing,"ADVFN plc, Owners",26 Throgmorton Street,,EC2 2AN,London,None,GBR,NaN,NaN,None
603,CScout Japan,"CScout Japan Co., Ltd.",Hanegi 2-17-8,Setagaya-ku,156-0042,Tokyo,None,JPN,NaN,NaN,None
604,My TV Shows,Lisbon Office,Rua RosÃ¡lia de Castro,,1700,Lisbon,None,PRT,38.752367,-9.146221,"{'type': 'Point', 'coordinates': [-9.1462209, ..."

In [98]:
df2.to_json("data/geopoints_offices.json",orient="records")

In [102]:
'''
query = {
   geopoint: {
     $near: {
       $geometry: {
          type: "Point" ,
          coordinates: [ 40.759095 , -73.9871507 ]
       },
       $maxDistance: 10000,
     }
   }
}
'''

'\nquery = {\n   geopoint: {\n     $near: {\n       $geometry: {\n          type: "Point" ,\n          coordinates: [ 40.759095 , -73.9871507 ]\n       },\n       $maxDistance: 10000,\n     }\n   }\n}\n'

In [109]:
timesSquare = [
    -73.9871507,
    40.759095
]
toGeoJson(*timesSquare)

{'type': 'Point', 'coordinates': [-73.9871507, 40.759095]}

In [112]:
def nearest(center, meters=10000, geofield="geopoint"):
    return {
       geofield: {
         "$near": {
           "$geometry": toGeoJson(*center),
           "$maxDistance": meters,
         }
       }
    }

In [113]:
nearest(timesSquare)

{'geopoint': {'$near': {'$geometry': {'type': 'Point',
    'coordinates': [-73.9871507, 40.759095]},
   '$maxDistance': 10000}}}

In [115]:
timesSquare = [
    -73.9871507,
    40.759095
]
db.offices.find_one(nearest(timesSquare))

{'_id': ObjectId('5f61f1b58387a03ea14ce2fc'),
 'name': 'Pictela',
 'description': 'Pictela New York',
 'address1': '770 Broadway',
 'address2': '',
 'zip_code': '10003',
 'city': 'New York',
 'state_code': 'NY',
 'country_code': 'USA',
 'latitude': 40.756054,
 'longitude': -73.986951,
 'geopoint': {'type': 'Point', 'coordinates': [-73.986951, 40.756054]}}

In [123]:
import requests

def geocodeText(query):
    try:
        res = requests.get(f"https://geocode.xyz/{query}?json=1")
        print(f"Geocode url:",res.url)
        data = res.json()
        point = [data["longt"],data["latt"]]
    except:
        raise ValueError("Cannot geocode query")
    return point

geocodeText("Times Square New York")

Geocode url: https://geocode.xyz/Times%20Square%20New%20York?json=1

['-73.95861', '40.68908']

In [128]:
location = geocodeText("Puerta del Sol Madrid")
list(db.offices.find(nearest(location)))

Geocode url: https://geocode.xyz/Puerta%20del%20Sol%20Madrid?json=1

[{'_id': ObjectId('5f61f1b58387a03ea14ce316'),
  'name': 'DAEDALUS - Data, Decisions and Language',
  'description': 'Headquarters',
  'address1': 'Lopez de Hoyos 15',
  'address2': '',
  'zip_code': '28006',
  'city': 'Madrid',
  'state_code': None,
  'country_code': 'ESP',
  'latitude': 40.4372542,
  'longitude': -3.6866654,
  'geopoint': {'type': 'Point', 'coordinates': [-3.6866654, 40.4372542]}},
 {'_id': ObjectId('5f61f1b58387a03ea14ce311'),
  'name': 'Unkasoft Advergaming',
  'description': 'Madrid Office (marketing)',
  'address1': 'Nieremberg 8, Bajo A',
  'address2': '',
  'zip_code': '28002',
  'city': 'Madrid',
  'state_code': None,
  'country_code': 'ESP',
  'latitude': 40.4474363,
  'longitude': -3.6714915,
  'geopoint': {'type': 'Point', 'coordinates': [-3.6714915, 40.4474363]}},
 {'_id': ObjectId('5f61f1b58387a03ea14ce202'),
  'name': 'Solaiemes',
  'description': 'Solaiemes Headquarter',
  'address1': 'Av/ General Fanjul',
  'address2': '2-Bis, office 3-5',
  'zip_code': '28044',
  'city': 'Madrid',
  'state_code': None,
  'country_code': 'ESP',
  'latitude': 40.382338,
  'longitude': -3.773844,
  'geopoint': {'type': 'Point', 'coordinates': [-3.773844, 40.382338]}}]